"""Add audit log and request note and service request tables

Revision ID: 78baa733b75c
Revises: 3a5f381eb169
Create Date: 2026-08-10 04:48:06.515820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78baa733b75c'
down_revision = '3a5f381eb169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_request_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('request_id != duplicate_of_request_id', name='check_not_self_duplicate'),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_request_id'], ['service_requests.request_id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.request_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('request_notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.request_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_notes')
    op.drop_table('audit_log')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
